import type { Metadata } from "next";
import "./globals.css";
import ThemeToggle from "../components/ThemeToggle";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-base-100 text-base-content">
        <header className="w-full flex justify-end items-center p-4">
          <ThemeToggle />
        </header>
        {children}
      </body>
    </html>
  );
}
